export enum ActionType {
  SHOW_MENU = "SHOW_MENU ",
  LOGIN = "LOGIN ",
  SEARCH = "SEARCH ",
  SCROLL = "SCROLL ",
  MODAL = "MODAL ",
  MODAL_SERIE = "MODAL_SERIE ",
  MODAL_REPORT = "MODAL_REPORT ",
}
